export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'
export const FETCH_QUIZ_FAILED = 'FETCH_QUIZ_FAILED'

export const ADD_RESULT = 'ADD_RESULT'

export const PLAY_AGAIN = 'PLAY_AGAIN'
